/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Hashtable;
import Classes.HashTableTitulos;
import Classes.ListaPalabrasClave;
import Classes.ListaAutores;
import Classes.HashTableTitulosAutores;
import Classes.ListaTitulos;
import Classes.NodoAutores;
import Classes.NodoTitulos;
import static GUI.Controlador.hashtable;
import static GUI.Controlador.hashtable3;
import static GUI.Controlador.listaAutores;
import static GUI.PalabrasClaves.hashtable;
import static GUI.PalabrasClaves.hashtable2;
/**
 *
 * @author enriq
 */
public class Autores extends javax.swing.JFrame {

    /**
     * Creates new form Autores
     */
    
    
    static Hashtable hashtable;
    static HashTableTitulos hashtable2;
    static HashTableTitulosAutores hashtable3;
    static ListaAutores listaAutores;
    static ListaPalabrasClave listaPalabrasClave;
    public Autores(Hashtable hashtable,HashTableTitulosAutores hashtable3,ListaAutores listaAutores, ListaPalabrasClave listaPalabrasClave) {
        initComponents();
        this.hashtable=hashtable;
        this.hashtable3=hashtable3;
        this.listaAutores=listaAutores;
        this.listaPalabrasClave=listaPalabrasClave;
        setLocationRelativeTo(null);
        
         NodoAutores pointer = listaAutores.getPrimero();

        
        while (pointer != null) {
            //recorre el grafo con un nodo aux pointer y se agregan las opciones en el jcombobox
            option1.addItem(pointer.getDato());
            

            pointer = pointer.getSiguiente();
        }
    }
        
        
        
        
        
        
        
        
        
        
        
        
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        option1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        option2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 200));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jPanel1.add(option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jPanel1.add(option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jButton3.setText("ATRAS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel1.setText("Busqueda por Autor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String palabra=option1.getSelectedItem().toString();
        
        
        
        int numero=hashtable3.NumeroHashtableTituloAutores(palabra);
        
        ListaTitulos listat=hashtable3.getArray()[numero];
        
        
        listat.Imprimir();
        NodoTitulos pointer=listat.getPrimero();
        
       
        while(pointer!=null){
            option2.addItem(pointer.getDato());
            pointer=pointer.getSiguiente();
        }
               
        
        AreaTexto.setText("");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        
        if (!option2.getSelectedItem().toString().equals("")){
            String palabra=option2.getSelectedItem().toString();
        
        int numero= hashtable.NumeroHashtable(palabra);
        
        String texto="";
        
        texto=texto+palabra+"\n"+"-----Autores-----\n";
        
        for (int i = 0; i < hashtable.getArray()[numero].getAuthors().length; i++) {
            
            texto=texto+hashtable.getArray()[numero].getAuthors()[i]+"\n";
        }
        
        texto=texto+"###Palabras Claves###\n";
        
        for (int i = 0; i < hashtable.getArray()[numero].getKeywords().length; i++) {
            
            texto=texto+"-"+hashtable.getArray()[numero].getKeywords()[i]+"\n";
        }
        
        AreaTexto.setText(texto);
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        Controlador window4= new Controlador( hashtable, hashtable2, listaPalabrasClave, listaAutores, hashtable3);
        window4.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autores( hashtable, hashtable3, listaAutores,listaPalabrasClave).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> option1;
    private javax.swing.JComboBox<String> option2;
    // End of variables declaration//GEN-END:variables
}
