/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.GUIFunctions;
import Classes.Hashtable;
import Classes.HashTableTitulos;
import Classes.ListaPalabrasClave;
import Classes.ListaAutores;
import Classes.HashTableTitulosAutores;
import Classes.ListaTitulos;
import Classes.NodoAutores;
import Classes.NodoTitulos;
import static GUI.Controlador.hashtable;
import static GUI.Controlador.hashtable3;
import static GUI.Controlador.listaAutores;
import static GUI.PalabrasClaves.hashtable;
import static GUI.PalabrasClaves.hashtable2;

/**
 *
 * @author enriq
 */
public class Autores extends javax.swing.JFrame {

    /**
     * Creates new form Autores
     */
    static Hashtable hashtable;
    static HashTableTitulos hashtable2;
    static HashTableTitulosAutores hashtable3;
    static ListaAutores listaAutores;
    static ListaPalabrasClave listaPalabrasClave;
    static Controlador Guimenu;
    GUIFunctions funciones=new GUIFunctions();

    public Autores(Hashtable hashtable, HashTableTitulosAutores hashtable3, ListaAutores listaAutores, ListaPalabrasClave listaPalabrasClave, Controlador Guimenu) {
        initComponents();
        this.hashtable = hashtable;
        this.hashtable3 = hashtable3;
        this.listaAutores = listaAutores;
        this.listaPalabrasClave = listaPalabrasClave;
        this.Guimenu=Guimenu;
        setLocationRelativeTo(null);

        NodoAutores pointer = listaAutores.getPrimero();

        while (pointer != null) {
            //recorre el grafo con un nodo aux pointer y se agregan las opciones en el jcombobox
            option1.addItem(pointer.getDato());

            pointer = pointer.getSiguiente();
        }
        ok.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        buscar = new javax.swing.JButton();
        option1 = new javax.swing.JComboBox<>();
        ok = new javax.swing.JButton();
        option2 = new javax.swing.JComboBox<>();
        atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 380, 230));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jPanel1.add(option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 310, -1));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jPanel1.add(option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, -1));

        atras.setText("Atrás");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        jLabel1.setText("Busqueda por Autor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel3.setText("Al ingresar, presiona primero el boton de buscar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/obit.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 780, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 770, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        option2.removeAllItems();
        
        String palabra = option1.getSelectedItem().toString();

        int numero = hashtable3.NumeroHashtableTituloAutores(palabra);

        ListaTitulos listat = hashtable3.getArray()[numero];

        listat.Imprimir();
        NodoTitulos pointer = listat.getPrimero();

        while (pointer != null) {
            option2.addItem(pointer.getDato());
            pointer = pointer.getSiguiente();
        }

        AreaTexto.setText("");
        ok.setVisible(true);


    }//GEN-LAST:event_buscarActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        if (!option2.getSelectedItem().toString().equals("")) {
            String texto= funciones.mostrarAutores(option2.getSelectedItem().toString(), hashtable);
            AreaTexto.setText(texto);

        }
    }//GEN-LAST:event_okActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed

        Guimenu.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autores(hashtable, hashtable3, listaAutores, listaPalabrasClave, Guimenu).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JButton atras;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    private javax.swing.JComboBox<String> option1;
    private javax.swing.JComboBox<String> option2;
    // End of variables declaration//GEN-END:variables
}
