/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Hashtable;
import Classes.Resumen;
import Classes.HashTableTitulos;
import Classes.HashTableTitulosAutores;

import static GUI.AnalizeGUI.hashtable;
import static GUI.PalabrasClaves.hashtable;
import static GUI.PalabrasClaves.hashtable2;
import static GUI.PalabrasClaves.listaPalabrasClave;
import static GUI.WelcomeGUI.hashtable;
import static GUI.WelcomeGUI.hashtable2;
import Classes.ListaPalabrasClave;
import Classes.ListaAutores;

/**
 *
 * @author enriq
 */
public class Controlador extends javax.swing.JFrame {

    /**
     * Creates new form Controlador
     */
    static Hashtable hashtable;
    static HashTableTitulos hashtable2;
    static HashTableTitulosAutores hashtable3;
    static ListaPalabrasClave listaPalabrasClave;
    static ListaAutores listaAutores;

    public Controlador(Hashtable hashtable, HashTableTitulos hashtable2, ListaPalabrasClave listaPalabrasClave, ListaAutores listaAutores, HashTableTitulosAutores hashtable3) {
        initComponents();
        setLocationRelativeTo(null);
        this.hashtable = hashtable;
        this.hashtable2 = hashtable2;
        this.listaPalabrasClave = listaPalabrasClave;
        this.listaAutores = listaAutores;
        this.hashtable3 = hashtable3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        analize = new javax.swing.JButton();
        keyword = new javax.swing.JButton();
        author = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        analize.setText("Analizar resumen");
        analize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizeActionPerformed(evt);
            }
        });
        jPanel1.add(analize, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 160, 40));

        keyword.setText("Buscar por palabra clave");
        keyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordActionPerformed(evt);
            }
        });
        jPanel1.add(keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 40));

        author.setText("Buscar por autor");
        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorActionPerformed(evt);
            }
        });
        jPanel1.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/obit.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 470, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizeActionPerformed

        AnalizeGUI window2 = new AnalizeGUI(hashtable, this);
        window2.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_analizeActionPerformed

    private void keywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordActionPerformed

        PalabrasClaves window4 = new PalabrasClaves(hashtable, hashtable2, listaPalabrasClave, this);
        window4.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_keywordActionPerformed

    private void authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorActionPerformed

        Autores window4 = new Autores(hashtable, hashtable3, listaAutores, listaPalabrasClave, this);
        window4.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_authorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controlador(hashtable, hashtable2, listaPalabrasClave, listaAutores, hashtable3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analize;
    private javax.swing.JButton author;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keyword;
    // End of variables declaration//GEN-END:variables
}
