/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.GUIFunctions;
import Classes.Hashtable;
import Classes.HashTableTitulos;
import Classes.ListaPalabrasClave;
import Classes.NodoTitulos;
import Classes.ListaTitulos;
import Classes.Resumen;
import Classes.NodoPalabrasClave;
import static GUI.Autores.hashtable;
import static GUI.Autores.hashtable2;
import static GUI.Autores.hashtable3;
import static GUI.Autores.listaAutores;
import static GUI.Autores.listaPalabrasClave;

/**
 *
 * @author enriq
 */
public class PalabrasClaves extends javax.swing.JFrame {

    /**
     * Creates new form PalabrasClaves
     */
    static Hashtable hashtable;
    static HashTableTitulos hashtable2;
    static ListaPalabrasClave listaPalabrasClave;
    static Controlador GUIMENU;
    GUIFunctions funciones = new GUIFunctions();

    public PalabrasClaves(Hashtable hashtable, HashTableTitulos hashtable2, ListaPalabrasClave listaPalabrasClave, Controlador GUIMENU) {
        initComponents();
        this.hashtable = hashtable;
        this.hashtable2 = hashtable2;
        this.listaPalabrasClave = listaPalabrasClave;
        this.GUIMENU = GUIMENU;
        optionmostrar.setVisible(false);
        setLocationRelativeTo(null);

        NodoPalabrasClave pointer = listaPalabrasClave.getPrimero();

        while (pointer != null) {
            //recorre el grafo con un nodo aux pointer y se agregan las opciones en el jcombobox
            option1.addItem(pointer.getDato());

            pointer = pointer.getSiguiente();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        option1 = new javax.swing.JComboBox<>();
        Buscar = new javax.swing.JButton();
        optionmostrar = new javax.swing.JButton();
        option2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        goback = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 360, 210));

        jPanel1.add(option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 290, -1));

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        optionmostrar.setText("OK");
        optionmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionmostrarActionPerformed(evt);
            }
        });
        jPanel1.add(optionmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        option2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2ActionPerformed(evt);
            }
        });
        jPanel1.add(option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 350, -1));

        jLabel1.setText("Palabras Clave");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, -1));

        goback.setText("Atrás");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });
        jPanel1.add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));

        jLabel3.setText("Al ingresar, presiona primero el boton de buscar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/obit.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 780, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        option2.removeAllItems();
        String palabra = option1.getSelectedItem().toString();
        int numero = hashtable2.NumeroHashtableTitulo(palabra);
        ListaTitulos listat = hashtable2.getArray()[numero];
        NodoTitulos pointer = listat.getPrimero();
        while (pointer != null) {
            option2.addItem(pointer.getDato());
            pointer = pointer.getSiguiente();
        }
        AreaTexto.setText("");
        optionmostrar.setVisible(true);

    }//GEN-LAST:event_BuscarActionPerformed

    private void optionmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionmostrarActionPerformed
        if (!option2.getSelectedItem().toString().equals("")) {
            String texto=funciones.optionMostrarKeywords(option2.getSelectedItem().toString(), hashtable);
            AreaTexto.setText(texto);
        }
    }//GEN-LAST:event_optionmostrarActionPerformed

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        GUIMENU.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_gobackActionPerformed

    private void option2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PalabrasClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PalabrasClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PalabrasClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PalabrasClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PalabrasClaves(hashtable, hashtable2, listaPalabrasClave, GUIMENU).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton goback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> option1;
    private javax.swing.JComboBox<String> option2;
    private javax.swing.JButton optionmostrar;
    // End of variables declaration//GEN-END:variables
}
