/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Classes.Hashtable;
import Classes.HashTableTitulos;
import Classes.ListaPalabrasClave;
import Classes.NodoTitulos;
import Classes.ListaTitulos;
import Classes.Resumen;
import Classes.NodoPalabrasClave;
import static GUI.Autores.hashtable;
import static GUI.Autores.hashtable2;
import static GUI.Autores.hashtable3;
import static GUI.Autores.listaAutores;
import static GUI.Autores.listaPalabrasClave;

/**
 *
 * @author enriq
 */
public class PalabrasClaves extends javax.swing.JFrame {

    /**
     * Creates new form PalabrasClaves
     */
    
    static Hashtable hashtable;
    static HashTableTitulos hashtable2;
    static ListaPalabrasClave listaPalabrasClave;
    
    public PalabrasClaves(Hashtable hashtable,HashTableTitulos hashtable2,ListaPalabrasClave listaPalabrasClave) {
        initComponents();
        this.hashtable=hashtable;
        this.hashtable2=hashtable2;
        this.listaPalabrasClave=listaPalabrasClave;
        setLocationRelativeTo(null);
        
        
        
        NodoPalabrasClave pointer = listaPalabrasClave.getPrimero();

        
        while (pointer != null) {
            //recorre el grafo con un nodo aux pointer y se agregan las opciones en el jcombobox
            option1.addItem(pointer.getDato());
            

            pointer = pointer.getSiguiente();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        option1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        optionmostrar = new javax.swing.JButton();
        option2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 210));

        jPanel1.add(option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        optionmostrar.setText("OK");
        optionmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionmostrarActionPerformed(evt);
            }
        });
        jPanel1.add(optionmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jPanel1.add(option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel1.setText("Palabras Clave");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 90, -1));

        jButton2.setText("ATRAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String palabra=option1.getSelectedItem().toString();
        
        
        
        int numero=hashtable2.NumeroHashtableTitulo(palabra);
        
        ListaTitulos listat=hashtable2.getArray()[numero];
        
        NodoTitulos pointer=listat.getPrimero();
        
       
        while(pointer!=null){
            option2.addItem(pointer.getDato());
            pointer=pointer.getSiguiente();
        }
        
        AreaTexto.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void optionmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionmostrarActionPerformed
        if (!option2.getSelectedItem().toString().equals("")){
        String palabra=option2.getSelectedItem().toString();
        
        int numero= hashtable.NumeroHashtable(palabra);
        
        String texto="";
        
        texto=texto+palabra+"\n"+"-----Autores-----\n";
        
        for (int i = 0; i < hashtable.getArray()[numero].getAuthors().length; i++) {
            
            texto=texto+hashtable.getArray()[numero].getAuthors()[i]+"\n";
        }
        
        texto=texto+"###Palabras Claves###\n";
        
        for (int i = 0; i < hashtable.getArray()[numero].getKeywords().length; i++) {
            
            texto=texto+"-"+hashtable.getArray()[numero].getKeywords()[i]+"\n";
        }
        
        AreaTexto.setText(texto);
        }
    }//GEN-LAST:event_optionmostrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Controlador window4= new Controlador( hashtable, hashtable2, listaPalabrasClave, listaAutores, hashtable3);
        window4.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PalabrasClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PalabrasClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PalabrasClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PalabrasClaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PalabrasClaves(hashtable,hashtable2,listaPalabrasClave).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> option1;
    private javax.swing.JComboBox<String> option2;
    private javax.swing.JButton optionmostrar;
    // End of variables declaration//GEN-END:variables
}
